books.genre=LUONGNM
%dev.books.genre=IT

quarkus.log.category."io.quarkus".level=INFO
%dev.quarkus.log.category."io.quarkus".level=INFO

quarkus.log.category."org.luongnm93".level=WARNING
#quarkus.banner.enabled=false
